### ISSUE TITLE
Cannot process odt file

### ISSUE THREAD

**Issue by arildm** [spraakbanken/mink-backend#50]
I call `run-sparv` after uploading an odt file, and I get:

> ERROR An error occurred while executing odt_import:parse:      sparv
>
> AttributeError: 'PosixPath' object has no attribute
'partition'
>
> To display further details when errors occur, run Sparv
with the '--log debug' argument.

This is the file:
[Regeringen press.odt](https://github.com/spraakbanken/mink-backend/files/8993270/Regeringen.press.odt)

The config is:

```yaml
metadata:
  id: mink-ZHdz2jnApa
  name:
    swe: Food
    eng: Food
  description:
    swe: ''
    eng: ''
import:
  importer: odt_import:parse
export:
  annotations:
  - <sentence>:misc.id
  - <token>:saldo.baseform
  - <token>:hunpos.pos
  - <token>:sensaldo.sentiment_label
  - <text> as text
```
